version: '3.8'
services:
  db:
    container_name: db
    env_file: .env
    restart: unless-stopped
    build:
      context: db
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
  api:
    container_name: api
    depends_on:
      - db
    env_file: .env
    restart: on-failure
    build:
      context: styli-api
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
  style-transfer:
    container_name: style-transfer
    env_file: .env
    build:
      context: styli-style-transfer
    ports:
      - "${STYLE_TRANSFER_HOST_PORT}:${STYLE_TRANSFER_CONTAINER_PORT}"
  segmentation:
    container_name: segmentation
    env_file: .env
    build:
      context: styli-segmentation
    ports:
      - "${SEGMENTATION_HOST_PORT}:${SEGMENTATION_CONTAINER_PORT}"
