version: '3.8'
services:
  db:
    container_name: db
    image: "mysql:latest"
    restart: unless-stopped
    env_file:
      - db.env
  api:
    container_name: api
    depends_on:
      - db
    restart: on-failure
    env_file:
      - api.env
    build:
      context: styli-api
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
  style-transfer:
    container_name: style-transfer
    restart: on-failure
    build:
      context: styli-style-transfer
  segmentation:
    container_name: segmentation
    restart: on-failure
    build:
      context: styli-segmentation
