version: '3.8'
services:
  db:
    container_name: db
    image: "mysql:latest"
    restart: always
    env_file:
      - db.env
  api:
    container_name: api
    depends_on:
      - db
    restart: always
    env_file:
      - api.env
    build:
      context: styli-api
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
  ui:
    container_name: ui
    depends_on:
      - api
    restart: always
    build:
      context: styli-ui
    ports:
      - "${UI_HOST_PORT}:${UI_CONTAINER_PORT}"
  style-transfer:
    container_name: style-transfer
    depends_on:
      - api
    restart: always
    env_file:
      - style-transfer.env
    build:
      context: styli-style-transfer
  segmentation:
    container_name: segmentation
    depends_on:
      - api
    restart: always
    build:
      context: styli-segmentation
