version: '3.3'
services:
  db:
    container_name: mysql-db
    build:
      context: /home/patryk/styli/db
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"