version: '3.8'
services:
#  db:
#    container_name: db
#    restart: unless-stopped
#    build:
#      context: db
#    ports:
#      - "3000:3306"
  api:
    container_name: api
    depends_on:
      - db
    restart: on-failure
    build:
      context: styli-api
    ports:
      - "8000:8000"
#  style-transfer:
#    container_name: style-transfer
#    build:
#      context: styli-style-transfer
#    ports:
#      - "8001:80"
#  segmentation:
#    container_name: segmentation
#    build:
#      context: styli-segmentation
#    ports:
#      - "8002:80"