spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8000
  tomcat:
    max-swallow-size: 100MB

styli:
  rootUrl: "/api"
  jwt:
    expirationInSeconds: 3600
  effects:
    - name: cartoonize
      url: http://${STYLE_TRANSFER_HOST}:${STYLE_TRANSFER_PORT}/st/cartoonization
      healthUrl: http://${STYLE_TRANSFER_HOST}:${STYLE_TRANSFER_PORT}/st/health
    - name: colorize
      url: http://${STYLE_TRANSFER_2_HOST}:${STYLE_TRANSFER_2_PORT}/st2/nst
      healthUrl: http://${STYLE_TRANSFER_2_HOST}:${STYLE_TRANSFER_2_PORT}/st2/health
    - name: background-swap
      url: http://${SEGMENTATION_HOST}:${SEGMENTATION_PORT}/sgm/segmentation
      healthUrl: http://${SEGMENTATION_HOST}:${SEGMENTATION_PORT}/sgm/health