spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/styli"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8000

styli:
  rootUrl: "/api"
  production: false
  secretKey: "helloDarknessMyOldFriend"
  tokenValidityInSecs: 100