spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/styli??autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8000

styli:
  rootUrl: "/api"
  jwt:
    expirationInSeconds: 3600
  effects:
    - name: cartoonize
      url: http://localhost:8001/st/cartoonization
      healthUrl: http://localhost:8001/st/health
    - name: background-swap
      url: http://localhost:8002/sgm/segmentation
      healthUrl: http://localhost:8002/sgm/health